name: Label Issues
on:
  issues:
    type:
      - opened
      - reopened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: label
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "ejemplo, papas fritas"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
